### ISSUE TITLE
Datum inzetbaar vertoont vreemd gedrag

### ISSUE THREAD

**Issue by FelixSedney** [JohnGorter/OpleidingsGenerator#1]
Datum Inzetbaar vertoont vreemd gedrag.   Stel startdatum is 16-10-2017. Berekende datum inzetbaar wordt dan   14-01-2018. De default selectie voor het traject laten staan. Preview ->   planning eindigt in week 52, ondanks dat datum inzetbaar op 14-01 staat.   Datum inzetbaar verplaatst naar 12-02-2018 en weer Preview. De extra   weken worden ingepland, maar UI geeft weer aan dat datum inzetbaar 14-01 is   (ipv 12-02).   Waar het op neerkomt is dat na iedere “preview opleidingplan” de   datum inzetbaar in de UI staat op datum indienst + 100 dagen. In de achtergrond   wordt wel rekening gehouden met de ingevoerde nieuwe einddatum.
--

**Comment by JohnGorter** [comment]
thanx, gefixed!
