### ISSUE TITLE
Waarschuwing bij navigeren

### ISSUE THREAD

**Issue by FelixSedney** [JohnGorter/OpleidingsGenerator#5]
Als je weg navigeert van de pagina opleidngsplan genereren en je komt terug dan ben je alle   ingevoerde data kwijt. Hier even voor waarschuwen in een dialoogje
--

**Comment by JohnGorter** [comment]
je ziet nu standaard een dialoog wanneer je van de pagina 'opleidingsplan genereren' weg navigeert.
