### ISSUE TITLE
Reeds opgeslagen opl plan updaten wordt niet opgeslagen

### ISSUE THREAD

**Issue by FelixSedney** [JohnGorter/OpleidingsGenerator#8]
Als ik een eerder opgeslagen opl. plan zoek -> detail -> aanpassen.
Nu maak ik aanpassingen (bijv voeg extra trainingen toe) dan is er geen opslaan button meer, maar wel een update button. Het lijkt of deze gedisabled is (het is grijs).
Als ik er op klik dan gebeurt er wel wat, maar als ik daarna de opl. plan weer inlaadt dan zitten de laatste wijzigingen niet in het bestand. Het lijkt er op dat er geen wijzigingen zijn opgeslagen.

**Comment by JohnGorter** [comment]
fixed in next version
