### ISSUE TITLE
Commentaar kan niet toegevoegd worden

### ISSUE THREAD

**Issue by FelixSedney** [JohnGorter/OpleidingsGenerator#9]
Bij iedere lijn in een gegenereerde opleidingsplan kun je via het potloodje (icoon) commentaar opnemen. Je gebruikt het oa om aan te geven wat de starter in het olc moet gaan doen. Als je commentaar aanmaakt kun je het niet meer opslaan. Dit heeft vroeger altijd wel gewerkt. Nu gebeurt er niets als je op opslaan klikt. De openstaande pop-up sluit ook niet.

**Comment by JohnGorter** [comment]
fixed in next release
